// <auto-generated />
using System;
using FluentRussian.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluentRussian.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240306111312_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FluentRussian.Web.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "залетает",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "улетает",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "приходит",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "выходит",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "выучила",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "учила",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "изучала",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "научилась",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "получилось",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "получился",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "получил",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "получила",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "Саша",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "у Саши",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "с Сашей",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "Саше",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "Автобус",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "Автобуса",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "Автобусом",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "Автобусу",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 21,
                            AnswerText = "стоматолога",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 22,
                            AnswerText = "стоматологу",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 23,
                            AnswerText = "со стоматологом",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 24,
                            AnswerText = "к стоматологу",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 25,
                            AnswerText = "за которым",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 26,
                            AnswerText = "к которому",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 27,
                            AnswerText = "от которого",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 28,
                            AnswerText = "с которым",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 29,
                            AnswerText = "около",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 30,
                            AnswerText = "через",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 31,
                            AnswerText = "за час",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 32,
                            AnswerText = "рядом с",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 33,
                            AnswerText = "тюльпана",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 34,
                            AnswerText = "тюльпаны",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 35,
                            AnswerText = "тюльпанов",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 36,
                            AnswerText = "тюльпан",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 37,
                            AnswerText = "экзамены",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 38,
                            AnswerText = "экзаменов",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 39,
                            AnswerText = "экзаменами",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 40,
                            AnswerText = "об экзаменах",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 41,
                            AnswerText = "на четыре недели",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 42,
                            AnswerText = "четыре недели",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 43,
                            AnswerText = "до четырёх недель",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 44,
                            AnswerText = "за четыре недели",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 45,
                            AnswerText = "через",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 46,
                            AnswerText = "на",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 47,
                            AnswerText = "за",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 48,
                            AnswerText = "в",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 49,
                            AnswerText = "едем",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 50,
                            AnswerText = "приедем",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 51,
                            AnswerText = "ездим",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 52,
                            AnswerText = "доезжаем",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 53,
                            AnswerText = "ехать",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 54,
                            AnswerText = "приехать",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 55,
                            AnswerText = "заехать",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 56,
                            AnswerText = "доехать",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 57,
                            AnswerText = "начнётся",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 58,
                            AnswerText = "начался",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 59,
                            AnswerText = "начинается",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 60,
                            AnswerText = "начинался",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 61,
                            AnswerText = "слышу",
                            IsCorrect = true,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 62,
                            AnswerText = "слушаю",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 63,
                            AnswerText = "услышу",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 64,
                            AnswerText = "послушаю",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 65,
                            AnswerText = "можно",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 66,
                            AnswerText = "можешь",
                            IsCorrect = true,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 67,
                            AnswerText = "нужен",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 68,
                            AnswerText = "нужно",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 69,
                            AnswerText = "так как",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 70,
                            AnswerText = "потому что",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 71,
                            AnswerText = "поэтому",
                            IsCorrect = true,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 72,
                            AnswerText = "из-за этого",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 73,
                            AnswerText = "если бы",
                            IsCorrect = true,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 74,
                            AnswerText = "когда",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 75,
                            AnswerText = "из-за того",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 76,
                            AnswerText = "потому что",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 77,
                            AnswerText = "что",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 78,
                            AnswerText = "как",
                            IsCorrect = true,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 79,
                            AnswerText = "о чём",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 80,
                            AnswerText = "какой",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 81,
                            AnswerText = "masculine",
                            IsCorrect = true,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 82,
                            AnswerText = "feminine",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 83,
                            AnswerText = "masculine",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 84,
                            AnswerText = "feminine",
                            IsCorrect = true,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 85,
                            AnswerText = "как дела́",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 86,
                            AnswerText = "приве́т",
                            IsCorrect = true,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 87,
                            AnswerText = "хорошо",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 88,
                            AnswerText = "one",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 89,
                            AnswerText = "two",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 90,
                            AnswerText = "three",
                            IsCorrect = true,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 91,
                            AnswerText = "true",
                            IsCorrect = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 92,
                            AnswerText = "false",
                            IsCorrect = true,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 93,
                            AnswerText = "хорошо",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 94,
                            AnswerText = "спаси́бо",
                            IsCorrect = true,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 95,
                            AnswerText = "чень",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 96,
                            AnswerText = "хорошо",
                            IsCorrect = true,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 97,
                            AnswerText = "спаси́бо",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 98,
                            AnswerText = "о́чень",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 99,
                            AnswerText = "хорошо",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 100,
                            AnswerText = "спаси́бо",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 101,
                            AnswerText = "о́чень",
                            IsCorrect = true,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 102,
                            AnswerText = "я говори́т",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 103,
                            AnswerText = "ты говори́т",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 104,
                            AnswerText = "он говори́т",
                            IsCorrect = true,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 105,
                            AnswerText = "all are correct",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 106,
                            AnswerText = "он говори́т",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 107,
                            AnswerText = "она́ говор́ит",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 108,
                            AnswerText = "both are correct",
                            IsCorrect = true,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 109,
                            AnswerText = "only nouns",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 110,
                            AnswerText = "nouns, pronouns and adjectives",
                            IsCorrect = true,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 111,
                            AnswerText = "only pronouns",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 112,
                            AnswerText = "ты",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 113,
                            AnswerText = "мне",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 114,
                            AnswerText = "тебя́",
                            IsCorrect = true,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 115,
                            AnswerText = "I don't have time.",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 116,
                            AnswerText = "Do you have time?",
                            IsCorrect = true,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 117,
                            AnswerText = "Don't you have time?",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 118,
                            AnswerText = "никогда́",
                            IsCorrect = true,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 119,
                            AnswerText = "никто́",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 120,
                            AnswerText = "нигде́",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 121,
                            AnswerText = "э́то некраси́во",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 122,
                            AnswerText = "э́то нехорошо́",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 123,
                            AnswerText = "э́то не пра́вда",
                            IsCorrect = true,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 124,
                            AnswerText = "диких животных",
                            IsCorrect = true,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 125,
                            AnswerText = "диких животнях",
                            IsCorrect = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 126,
                            AnswerText = "о этом",
                            IsCorrect = true,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 127,
                            AnswerText = "об этом",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 128,
                            AnswerText = "о эте",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 129,
                            AnswerText = "первый",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 130,
                            AnswerText = "второй",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 131,
                            AnswerText = "третий",
                            IsCorrect = true,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 132,
                            AnswerText = "на этом году",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 133,
                            AnswerText = "в этом году",
                            IsCorrect = true,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 134,
                            AnswerText = "в этом годе",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 135,
                            AnswerText = "маленьких ребёнках",
                            IsCorrect = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 136,
                            AnswerText = "маленьких детях",
                            IsCorrect = true,
                            QuestionId = 40
                        });
                });

            modelBuilder.Entity("FluentRussian.Web.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageLevel")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("57662390-40e7-4f0f-bd24-08dc3db7d571"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df8b7716-5f40-4451-bc43-1f5ca30b8143",
                            Email = "a1@test.bg",
                            EmailConfirmed = false,
                            LanguageLevel = 1,
                            LockoutEnabled = true,
                            NormalizedEmail = "A1@TEST.BG",
                            NormalizedUserName = "A1@TEST.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEOvQGNhY201NMsXhgHAN+rAwdAu94Va0trMZ0rpr3ukW/vl9dz50jAUOPTI8gq0ROA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QB6WIL4W4X2WZOFFL6YGNFEI3Q5I64KF",
                            TwoFactorEnabled = false,
                            UserName = "a1@test.bg"
                        },
                        new
                        {
                            Id = new Guid("33822001-5e21-49fb-bded-08dc3db33dc5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8603cf59-2285-4a92-9f0d-2a0ee77004e9",
                            Email = "a2@test.bg",
                            EmailConfirmed = false,
                            LanguageLevel = 2,
                            LockoutEnabled = true,
                            NormalizedEmail = "A2@TEST.BG",
                            NormalizedUserName = "A2@TEST.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEMZ7tvlP/849uTDSn/0wkgPLLVYdZnDuLQmXwBCherHABV3xq2O7xFWg07vMC8yexw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QJXYM6QEPMJTWNNPVUE5NSKKEFSCRUBV",
                            TwoFactorEnabled = false,
                            UserName = "a2@test.bg"
                        },
                        new
                        {
                            Id = new Guid("3f3986a6-3ac1-4677-f2b0-08dc3dca209f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0d75c37-1493-42ad-9161-e32b174452c9",
                            Email = "b1@test.bg",
                            EmailConfirmed = false,
                            LanguageLevel = 3,
                            LockoutEnabled = true,
                            NormalizedEmail = "B1@TEST.BG",
                            NormalizedUserName = "B1@TEST.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEDVJN2dN5Vq3tKxw6gXNwWzLU0y4CS+5BRaBRP77gDR2lzo+i6RWUfM7YhVEzdyEgg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E3JW4QXMVNJW7P5HO2BTPA4X37ZL7XQM",
                            TwoFactorEnabled = false,
                            UserName = "b1@test.bg"
                        },
                        new
                        {
                            Id = new Guid("44f5adda-8f96-4627-5368-08dc3dbdaea7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f4b53351-ceec-4fbe-a26c-f131a25fe64d",
                            Email = "b2@test.bg",
                            EmailConfirmed = false,
                            LanguageLevel = 4,
                            LockoutEnabled = true,
                            NormalizedEmail = "B2@TEST.BG",
                            NormalizedUserName = "B2@TEST.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ3e8S8lzffJnTLs5iWvV+FjcS4XuZLEsKVjC4ovWlz0JmHG/DjKHpjbT2v8KuXcDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NHK5PWVZQFDH4EUQMCCGFIW6YVLPQIFL",
                            TwoFactorEnabled = false,
                            UserName = "b2@test.bg"
                        });
                });

            modelBuilder.Entity("FluentRussian.Web.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionText = "В пятницу Екатерина __________ в Берлин.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 2,
                            QuestionText = "Моя дочь очень рано __________ читать.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 3,
                            QuestionText = "Вчера у меня __________ вкусный торт..",
                            TestId = 1
                        },
                        new
                        {
                            Id = 4,
                            QuestionText = "Ты помнишь, что __________ сегодня экзамен?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 5,
                            QuestionText = "__________ нет уже двадцать минут!",
                            TestId = 1
                        },
                        new
                        {
                            Id = 6,
                            QuestionText = "У меня болит зуб, завтра я пойду __________ .",
                            TestId = 1
                        },
                        new
                        {
                            Id = 7,
                            QuestionText = "У меня есть друг, __________ я встречаюсь один раз в год.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 8,
                            QuestionText = "Мои занятия танцами начинаются __________ семи вечера.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 9,
                            QuestionText = "На день рождения Ольге подарили 23 __________.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 10,
                            QuestionText = "В деканате уже есть расписание __________ ?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 11,
                            QuestionText = "Мы живём в Москве уже  __________ .",
                            TestId = 1
                        },
                        new
                        {
                            Id = 12,
                            QuestionText = "Я опаздываю, мой самолёт вылетает __________ 20 минут.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 13,
                            QuestionText = "Каждые полгода мы  __________ на море.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 14,
                            QuestionText = "На метро мы сможем  __________ до центра за 20 минут.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 15,
                            QuestionText = "Спектакль __________ давно, вы уже опоздали.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 16,
                            QuestionText = "Говорите громче, я вас плохо __________ .",
                            TestId = 1
                        },
                        new
                        {
                            Id = 17,
                            QuestionText = "Ты __________ пойти в парк, когда закончишь домашнюю работу. ",
                            TestId = 1
                        },
                        new
                        {
                            Id = 18,
                            QuestionText = "Сегодня хорошая погода,  __________ мы поедем кататься на велосипеде.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 19,
                            QuestionText = "Я мог бы приготовить ужин, __________ успел.",
                            TestId = 1
                        },
                        new
                        {
                            Id = 20,
                            QuestionText = "Вы не знаете, __________ зовут нашего нового преподавателя?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 21,
                            QuestionText = "The word ру́сский is of ... gender?",
                            TestId = 2
                        },
                        new
                        {
                            Id = 22,
                            QuestionText = "The word ру́сская is of ... gender.",
                            TestId = 2
                        },
                        new
                        {
                            Id = 23,
                            QuestionText = "How do you say \"hi\" in Russian?",
                            TestId = 2
                        },
                        new
                        {
                            Id = 24,
                            QuestionText = "How many genders are there in Russian?",
                            TestId = 2
                        },
                        new
                        {
                            Id = 25,
                            QuestionText = "In Russian the verb \"быть\" is always omitted.",
                            TestId = 2
                        },
                        new
                        {
                            Id = 26,
                            QuestionText = "How do you say \"thank you\" in Russian?",
                            TestId = 3
                        },
                        new
                        {
                            Id = 27,
                            QuestionText = "How do you say \"well\" in Russian?",
                            TestId = 3
                        },
                        new
                        {
                            Id = 28,
                            QuestionText = "How do you say \"very\" in Russian?",
                            TestId = 3
                        },
                        new
                        {
                            Id = 29,
                            QuestionText = "Choose the correct sentence.",
                            TestId = 3
                        },
                        new
                        {
                            Id = 30,
                            QuestionText = "Choose the correct sentence.",
                            TestId = 3
                        },
                        new
                        {
                            Id = 31,
                            QuestionText = "What can be declined in Russian?",
                            TestId = 4
                        },
                        new
                        {
                            Id = 32,
                            QuestionText = "Complete the sentence: У меня́ есть время́ для ...",
                            TestId = 4
                        },
                        new
                        {
                            Id = 33,
                            QuestionText = "What does \"У тебя́ есть вре́мя?\" mean?",
                            TestId = 4
                        },
                        new
                        {
                            Id = 34,
                            QuestionText = "How do you say \"never\" in Russian?",
                            TestId = 4
                        },
                        new
                        {
                            Id = 35,
                            QuestionText = "How do you say \"It's not true\" in Russian?",
                            TestId = 4
                        },
                        new
                        {
                            Id = 36,
                            QuestionText = "What is Prepositional plural for \"дикое животное\"?",
                            TestId = 5
                        },
                        new
                        {
                            Id = 37,
                            QuestionText = "Which options is correct? Я думаю ...",
                            TestId = 5
                        },
                        new
                        {
                            Id = 38,
                            QuestionText = "Which cardinal numeral does not have the ending \"ом\" in prepositional?",
                            TestId = 5
                        },
                        new
                        {
                            Id = 39,
                            QuestionText = "How do you say \"this year\" in Russian?",
                            TestId = 5
                        },
                        new
                        {
                            Id = 40,
                            QuestionText = "Finish the following sentence: Я читаю о ...",
                            TestId = 5
                        });
                });

            modelBuilder.Entity("FluentRussian.Web.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Entry Level"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "A2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "B1"
                        },
                        new
                        {
                            Id = 5,
                            Name = "B2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FluentRussian.Web.Models.Answer", b =>
                {
                    b.HasOne("FluentRussian.Web.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FluentRussian.Web.Models.Question", b =>
                {
                    b.HasOne("FluentRussian.Web.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FluentRussian.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FluentRussian.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluentRussian.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FluentRussian.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FluentRussian.Web.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FluentRussian.Web.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
